## application.properties
#spring.profiles.include=secrets

server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3310/tripdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.default_batch_fetch_size=100

# Google Place API Key
google.api.key=xx

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=xx
spring.security.oauth2.client.registration.google.client-secret=xx

spring.security.oauth2.client.registration.google.scope=profile,email

# Kakao OAuth2
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.client-id=a07decb336709e3b5713679fd5a8ea74
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.scope=profile_nickname, account_email

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

# ??
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always

# OpenAi
openai.api-key=xx
openai.base-url=https://api.openai.com/v1
openai.model=gpt-4.1-mini
openai.max-output-tokens=2000

# Kakao Local
kakao.local.base-url=https://dapi.kakao.com
kakao.local.rest-api-key=xx


# JWT
jwt.secret=ThisIsVeryLongSecretKeyForJwtAuthentication123!
jwt.access-token-expiration=9000000
jwt.refresh-token-expiration=6048000000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=12345678

# Image Limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ResetPassword
spring.mail.host=smtp.gmail.com
spring.mail.post=587
spring.mail.username=xx
spring.mail.password=xx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true