server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3310/tripdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Google Place API Key
google.api.key=git push origin develop

# Google OAuth2 API Key

spring.security.oauth2.client.registration.google.client-id=????_ID
spring.security.oauth2.client.registration.google.client-secret=????_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email

# JWT
jwt.secret=bXktc3VwZXItbG9uZy1zdXBlci1zZWNyZXQta2V5LWZvci1qd3QtaHMyNTYtMTIzNDU2Nzg5MA==
jwt.access-token-expiration=3600000